/**
 * @file components/Worker/Tag/test.mock.js
 * @description WorkerTagコンポーネントのテスト用モックデータ
 * - Employeeクラスのインスタンスとして様々なケースをカバー
 */
import { Employee, Certification } from "@/schemas";

/**
 * 従業員モックデータ
 * - remarksに各ケースの説明を記載
 */
export const mockEmployees = [
  // ケース1: 通常の従業員（警備員登録あり）
  new Employee({
    docId: "abc123def456ghi789jkl",
    code: "E001",
    lastName: "山田",
    firstName: "太郎",
    lastNameKana: "ヤマダ",
    firstNameKana: "タロウ",
    displayName: "山田太郎",
    gender: "male",
    dateOfBirth: new Date("1985-04-15"),
    zipcode: "160-0023",
    prefCode: "13",
    city: "新宿区",
    address: "西新宿1-1-1",
    building: "新宿ビル101",
    mobile: "090-1234-5678",
    email: "yamada.taro@example.com",
    dateOfHire: new Date("2015-04-01"),
    employmentStatus: Employee.STATUS_ACTIVE,
    title: "警備員",
    hasSecurityGuardRegistration: true,
    dateOfSecurityGuardRegistration: new Date("2015-05-01"),
    bloodType: "A",
    emergencyContactName: "山田花子",
    emergencyContactRelation: "spouse",
    emergencyContactRelationDetail: "妻",
    emergencyContactAddress: "東京都新宿区西新宿1-1-1",
    emergencyContactPhone: "090-9876-5432",
    domicile: "東京都新宿区",
    securityCertifications: [],
    remarks: "【モック】通常の従業員（警備員登録あり、資格なし）",
  }),

  // ケース2: 外国人従業員
  new Employee({
    docId: "mno234pqr567stu890vwx",
    code: "E002",
    lastName: "田中",
    firstName: "ジョン",
    lastNameKana: "タナカ",
    firstNameKana: "ジョン",
    displayName: "田中ジョン",
    gender: "male",
    dateOfBirth: new Date("1990-08-20"),
    zipcode: "150-0002",
    prefCode: "13",
    city: "渋谷区",
    address: "渋谷2-2-2",
    building: "",
    mobile: "080-2345-6789",
    email: "tanaka.john@example.com",
    dateOfHire: new Date("2020-06-01"),
    employmentStatus: Employee.STATUS_ACTIVE,
    title: "警備員",
    isForeigner: true,
    foreignName: "John Smith",
    nationality: "アメリカ",
    residenceStatus: "技術・人文知識・国際業務",
    periodOfStay: new Date("2027-06-01"),
    hasSecurityGuardRegistration: true,
    dateOfSecurityGuardRegistration: new Date("2020-07-01"),
    bloodType: "B",
    emergencyContactName: "Mary Smith",
    emergencyContactRelation: "other",
    emergencyContactRelationDetail: "母",
    emergencyContactAddress: "アメリカ合衆国カリフォルニア州",
    emergencyContactPhone: "+1-234-567-8901",
    domicile: "東京都渋谷区",
    securityCertifications: [],
    remarks: "【モック】外国人従業員（在留資格あり）",
  }),

  // ケース3: 退職者
  new Employee({
    docId: "yza345bcd678efg901hij",
    code: "E003",
    lastName: "佐藤",
    firstName: "健太",
    lastNameKana: "サトウ",
    firstNameKana: "ケンタ",
    displayName: "佐藤健太",
    gender: "male",
    dateOfBirth: new Date("1970-03-10"),
    zipcode: "100-0001",
    prefCode: "13",
    city: "千代田区",
    address: "千代田3-3-3",
    building: "",
    mobile: "090-3456-7890",
    email: "sato.kenta@example.com",
    dateOfHire: new Date("2000-04-01"),
    employmentStatus: Employee.STATUS_TERMINATED,
    title: "班長",
    dateOfTermination: new Date("2025-03-31"),
    reasonOfTermination: "定年退職",
    hasSecurityGuardRegistration: true,
    dateOfSecurityGuardRegistration: new Date("2000-05-01"),
    bloodType: "O",
    emergencyContactName: "佐藤由美",
    emergencyContactRelation: "spouse",
    emergencyContactRelationDetail: "妻",
    emergencyContactAddress: "東京都千代田区千代田3-3-3",
    emergencyContactPhone: "090-8765-4321",
    domicile: "東京都千代田区",
    securityCertifications: [],
    remarks: "【モック】退職者（定年退職）",
  }),

  // ケース4: 資格保有者（複数資格）
  new Employee({
    docId: "klm456nop789qrs012tuv",
    code: "E004",
    lastName: "鈴木",
    firstName: "一郎",
    lastNameKana: "スズキ",
    firstNameKana: "イチロウ",
    displayName: "鈴木一郎",
    gender: "male",
    dateOfBirth: new Date("1988-12-05"),
    zipcode: "220-0012",
    prefCode: "14",
    city: "横浜市西区",
    address: "みなとみらい4-4-4",
    building: "横浜タワー202",
    mobile: "080-4567-8901",
    email: "suzuki.ichiro@example.com",
    dateOfHire: new Date("2012-04-01"),
    employmentStatus: Employee.STATUS_ACTIVE,
    title: "隊長",
    hasSecurityGuardRegistration: true,
    dateOfSecurityGuardRegistration: new Date("2012-05-01"),
    bloodType: "AB",
    emergencyContactName: "鈴木美咲",
    emergencyContactRelation: "spouse",
    emergencyContactRelationDetail: "妻",
    emergencyContactAddress: "神奈川県横浜市西区みなとみらい4-4-4",
    emergencyContactPhone: "080-7654-3210",
    domicile: "神奈川県横浜市西区",
    securityCertifications: [
      new Certification({
        code: "C001",
        name: "警備員指導教育責任者（1号）",
        abbreviation: "指導教育1号",
      }),
      new Certification({
        code: "C002",
        name: "機械警備業務管理者",
        abbreviation: "機械管理者",
      }),
    ],
    remarks:
      "【モック】資格保有者（複数資格：指導教育責任者、機械警備業務管理者）",
  }),

  // ケース5: 警備員登録なし（事務職）
  new Employee({
    docId: "wxy567zab890cde123fgh",
    code: "E005",
    lastName: "高橋",
    firstName: "さくら",
    lastNameKana: "タカハシ",
    firstNameKana: "サクラ",
    displayName: "高橋さくら",
    gender: "female",
    dateOfBirth: new Date("1995-07-22"),
    zipcode: "530-0001",
    prefCode: "27",
    city: "大阪市北区",
    address: "梅田5-5-5",
    building: "梅田ビル3F",
    mobile: "090-5678-9012",
    email: "takahashi.sakura@example.com",
    dateOfHire: new Date("2018-04-01"),
    employmentStatus: Employee.STATUS_ACTIVE,
    title: "事務員",
    hasSecurityGuardRegistration: false,
    remarks: "【モック】警備員登録なし（事務職員）",
  }),

  // ケース6: 新入社員
  new Employee({
    docId: "ijk678lmn901opq234rst",
    code: "E006",
    lastName: "伊藤",
    firstName: "大輔",
    lastNameKana: "イトウ",
    firstNameKana: "ダイスケ",
    displayName: "伊藤大輔",
    gender: "male",
    dateOfBirth: new Date("2002-11-30"),
    zipcode: "460-0008",
    prefCode: "23",
    city: "名古屋市中区",
    address: "栄6-6-6",
    building: "",
    mobile: "080-6789-0123",
    email: "ito.daisuke@example.com",
    dateOfHire: new Date("2025-04-01"),
    employmentStatus: Employee.STATUS_ACTIVE,
    title: "警備員",
    hasSecurityGuardRegistration: true,
    dateOfSecurityGuardRegistration: new Date("2025-05-01"),
    bloodType: "A",
    emergencyContactName: "伊藤正明",
    emergencyContactRelation: "parent",
    emergencyContactRelationDetail: "父",
    emergencyContactAddress: "愛知県名古屋市中区栄6-6-6",
    emergencyContactPhone: "090-6543-2109",
    domicile: "愛知県名古屋市中区",
    securityCertifications: [],
    remarks: "【モック】新入社員（2025年4月入社、勤続1年未満）",
  }),

  // ケース7: ベテラン従業員（勤続20年以上）
  new Employee({
    docId: "uvw789xyz012abc345def",
    code: "E007",
    lastName: "渡辺",
    firstName: "誠",
    lastNameKana: "ワタナベ",
    firstNameKana: "マコト",
    displayName: "渡辺誠",
    gender: "male",
    dateOfBirth: new Date("1968-05-18"),
    zipcode: "810-0001",
    prefCode: "40",
    city: "福岡市中央区",
    address: "天神7-7-7",
    building: "天神マンション405",
    mobile: "090-7890-1234",
    email: "watanabe.makoto@example.com",
    dateOfHire: new Date("2003-04-01"),
    employmentStatus: Employee.STATUS_ACTIVE,
    title: "部長",
    hasSecurityGuardRegistration: true,
    dateOfSecurityGuardRegistration: new Date("2003-05-01"),
    bloodType: "B",
    emergencyContactName: "渡辺恵子",
    emergencyContactRelation: "spouse",
    emergencyContactRelationDetail: "妻",
    emergencyContactAddress: "福岡県福岡市中央区天神7-7-7",
    emergencyContactPhone: "090-5432-1098",
    domicile: "福岡県福岡市中央区",
    securityCertifications: [
      new Certification({
        code: "C003",
        name: "警備員指導教育責任者（2号）",
        abbreviation: "指導教育2号",
      }),
    ],
    remarks: "【モック】ベテラン従業員（勤続20年以上、管理職）",
  }),

  // ケース8: 外国人＋資格保有者
  new Employee({
    docId: "ghi890jkl123mno456pqr",
    code: "E008",
    lastName: "李",
    firstName: "明",
    lastNameKana: "リ",
    firstNameKana: "ミン",
    displayName: "李明",
    gender: "male",
    dateOfBirth: new Date("1987-02-14"),
    zipcode: "650-0001",
    prefCode: "28",
    city: "神戸市中央区",
    address: "三宮8-8-8",
    building: "三宮ハイツ501",
    mobile: "080-8901-2345",
    email: "li.ming@example.com",
    dateOfHire: new Date("2016-04-01"),
    employmentStatus: Employee.STATUS_ACTIVE,
    title: "副隊長",
    isForeigner: true,
    foreignName: "Li Ming",
    nationality: "中国",
    residenceStatus: "永住者",
    periodOfStay: null, // 永住者は期限なし
    hasSecurityGuardRegistration: true,
    dateOfSecurityGuardRegistration: new Date("2016-05-01"),
    bloodType: "O",
    emergencyContactName: "李華",
    emergencyContactRelation: "spouse",
    emergencyContactRelationDetail: "妻",
    emergencyContactAddress: "兵庫県神戸市中央区三宮8-8-8",
    emergencyContactPhone: "080-4321-0987",
    domicile: "兵庫県神戸市中央区",
    securityCertifications: [
      new Certification({
        code: "C004",
        name: "施設警備業務検定1級",
        abbreviation: "施設1級",
      }),
    ],
    remarks: "【モック】外国人＋資格保有者（永住者、施設警備1級）",
  }),

  // ケース9: 女性警備員（資格あり）
  new Employee({
    docId: "stu901vwx234yza567bcd",
    code: "E009",
    lastName: "中村",
    firstName: "美咲",
    lastNameKana: "ナカムラ",
    firstNameKana: "ミサキ",
    displayName: "中村美咲",
    gender: "female",
    dateOfBirth: new Date("1992-09-08"),
    zipcode: "060-0001",
    prefCode: "01",
    city: "札幌市中央区",
    address: "北1条西9-9-9",
    building: "",
    mobile: "090-9012-3456",
    email: "nakamura.misaki@example.com",
    dateOfHire: new Date("2017-04-01"),
    employmentStatus: Employee.STATUS_ACTIVE,
    title: "警備員",
    hasSecurityGuardRegistration: true,
    dateOfSecurityGuardRegistration: new Date("2017-05-01"),
    bloodType: "A",
    emergencyContactName: "中村健一",
    emergencyContactRelation: "parent",
    emergencyContactRelationDetail: "父",
    emergencyContactAddress: "北海道札幌市中央区北1条西9-9-9",
    emergencyContactPhone: "090-3210-9876",
    domicile: "北海道札幌市中央区",
    securityCertifications: [
      new Certification({
        code: "C005",
        name: "交通誘導警備業務検定2級",
        abbreviation: "交通誘導2級",
      }),
    ],
    remarks: "【モック】女性警備員（交通誘導2級資格保有）",
  }),

  // ケース10: 期間限定雇用（在留期限間近の外国人）
  new Employee({
    docId: "cde678efg901hij234klm",
    code: "E010",
    lastName: "グエン",
    firstName: "タン",
    lastNameKana: "グエン",
    firstNameKana: "タン",
    displayName: "グエンタン",
    gender: "male",
    dateOfBirth: new Date("1998-06-25"),
    zipcode: "330-0001",
    prefCode: "11",
    city: "さいたま市大宮区",
    address: "大宮10-10-10",
    building: "大宮アパート201",
    mobile: "080-0123-4567",
    email: "nguyen.tan@example.com",
    dateOfHire: new Date("2023-04-01"),
    employmentStatus: Employee.STATUS_ACTIVE,
    title: "警備員",
    isForeigner: true,
    foreignName: "Nguyen Van Tan",
    nationality: "ベトナム",
    residenceStatus: "特定技能1号",
    periodOfStay: new Date("2026-03-31"), // 期限間近
    hasSecurityGuardRegistration: true,
    dateOfSecurityGuardRegistration: new Date("2023-05-01"),
    bloodType: "B",
    emergencyContactName: "Nguyen Thi Hoa",
    emergencyContactRelation: "other",
    emergencyContactRelationDetail: "母",
    emergencyContactAddress: "ベトナム国ハノイ市",
    emergencyContactPhone: "+84-123-456-789",
    domicile: "埼玉県さいたま市大宮区",
    securityCertifications: [],
    remarks: "【モック】在留期限間近の外国人（特定技能1号、2026年3月期限）",
  }),
];

/**
 * 外注先作業員モックデータ（将来的に使用予定）
 */
export const mockOutsourcers = [];
